# Generated by Django 2.2.6 on 2019-11-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('DeptID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
    ]
