# Generated by Django 2.2.6 on 2019-11-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0002_departmentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityModel',
            fields=[
                ('FacilityID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('RoomID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
    ]
