# Generated by Django 2.2.6 on 2019-11-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0003_facilitymodel_rolemodel_roommodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartmentModel',
            new_name='DeptModel',
        ),
    ]
