# Generated by Django 2.2.6 on 2019-11-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0005_empmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmodel',
            name='Phone_No',
            field=models.IntegerField(default=False),
        ),
    ]
