# Generated by Django 2.2.6 on 2019-11-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0006_empmodel_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='Facility',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='empmodel',
            name='Phone_No',
            field=models.IntegerField(),
        ),
    ]
